export{default as MBut} from "./multibutton/Mbutton";
export{default as OR} from"./orButton/OrButton";
export{default as DEL} from "./delButton/DelButton";
export{default as Search} from "./searchBar/SearchBar";
export{default as UserText1} from "./text1/Text1";
export{default as UserText2} from "./text2/Text2";
export{default as UserAge} from "./text-number/TextNumber";
export{default as CheckBox} from "./checkbox/Checkbox";
export {default as OpenLi} from "./openlistbtn/Openllbtn";
export{default as  EmerBtn} from "./emergencybtn/Emergencybtn";
export{default as Btn} from"./btn/Btn";
export{default as LiBTN} from"./libtn/Libtn";
export{default as Table_patients} from "./table/Table_patient";
